eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wiskeycq/config-repo
          username: wiskeycq
          password: cq921208
          basedir: D:\学习视频\basedir
  rabbitmq:
      host: localhost
      port: 5673
      username: guest
      password: guest
management:
  endpoints:
    web:
      exposure:
        include: "*"